name: pyfunceble-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pyfunceble-dev>=4.0.2b1
      - black
      - wheel
      - mypdns
      - Pygments>=2.0
variables:
