name: pyfunceble
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pyfunceble>=4.0.1
      - black
      - wheel
      - mypdns
      - Pygments>=2.0
variables:
